### ISSUE TITLE
Gaussian Input generator

### ISSUE THREAD

**Issue by herbertludowieg** [exa-analytics/exatomic#125]
Hey guys so I am trying to generate a bunch of Gaussian inputs to do some SP calculations. I just wanted to see if I'm doing this right.
```
import exatomic
from exatomic import gaussian
path = "path_to_some_xyz_file"
uni = exatomic.XYZ(path).to_universe()
gaussian.Input(uni)
```
When I do this it throws the following error
```
TypeError: Unknown type for arg data: <class 'exatomic.core.universe.Universe'>
```
When I just input the path of the xyz file it prints out the original file. Also, if I try `gaussian.Input(uni=uni)` it throws `TypeError: __init__() got an unexpected keyword argument 'uni'`. Thanks for your help.

**Comment by tjduigna** [comment]
Try the bound method on the Input class, the .from_universe method ought to
accept a unique as the first and only required argument

**Comment by herbertludowieg** [comment]
Yes, I completely forgot about that one. Thank you.
