### ISSUE TITLE
Compute Zero-Point Vibrational Corrections

### ISSUE THREAD

**Issue by herbertludowieg** [exa-analytics/exatomic#128]
Implement code that can be used to perform Vibrational Averaging as explained in the paper J. Phys. Chem. A, 2005, 109 (38), pp 8617–8623 (DOI: 10.1021/jp051685y).
Re-write of Perl and FORTRAN scripts by the authors to a python format.

**Comment by tjduigna** [comment]
If you get a moment, you could update this issue with a road map to track the overall progress of this as PRs come in referencing this issue.

**Comment by herbertludowieg** [comment]
Sounds good I'll try working on that unfortunately one of my fans broke so I'll be without a computer for some time. But I'll get to everything as soon as I can.

**Comment by herbertludowieg** [comment]
Closed by VROA PR
