### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by avmarchenko** [exa-analytics/exatomic#130]
I propose we move away from restructured text (rst) files being written by hand. We can use `sphinx-apidoc` to generate rst files for all subpackages/modules. A slight modification to the index.rst will enable docs to use the programmatically generated API docs. We should keep the getting started and other helpful pieces of course (sphinx-apidoc is for api only).

**Comment by tjduigna** [comment]
This makes a lot of sense.  It ought to be a quick and easy contribution that would really spruce up the docs.
