### ISSUE TITLE
NWChem frequency and gradient parser

### ISSUE THREAD

**Issue by herbertludowieg** [exa-analytics/exatomic#134]
**Is your feature request related to a problem? Please describe.**
It would be good if we could have a frequency parser for NWChem so we could use the vibrational averaging code from more than one programs frequency calculations.

**Describe the solution you'd like**
A parser similar to Gaussian that could give the normal mode displacements reported by NWChem.

**Describe alternatives you've considered**
Generate a spaghetti code that uses crude searching methods.

**Comment by avmarchenko** [comment]
This is a good suggestion. Can we get an example output or two (covering different cases) here or on slack? That would make development and testing much easier.

**Comment by herbertludowieg** [comment]
Yes I forgot to add that here is a water molecule example. 
[nwchem-water.zip](https://github.com/exa-analytics/exatomic/files/2729018/nwchem-water.zip)

**Comment by tjduigna** [comment]
👍  look forward to a PR
