### ISSUE TITLE
Quirks of the travis build

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exatomic#136]
**Describe the bug**
This is just a minor issue with the way the .travis.yml builds exatomic.  When mimicking the installation, the command to `pip install -e exa/` requires a pip install of the following packages:
```
Installing collected packages: scipy, networkx, kiwisolver, cycler, matplotlib, seaborn, exa
  Running setup.py develop for exa
```

**To Reproduce**

Run the commands in the .travis.yml starting from:
https://github.com/exa-analytics/exatomic/blob/815b921256d9c064bf974f6fc1227734435d9dc1/.travis.yml#L34

to

https://github.com/exa-analytics/exatomic/blob/815b921256d9c064bf974f6fc1227734435d9dc1/.travis.yml#L44

**Expected behavior**
I expected there to be no additional dependencies for pip to install when installing the git clone of exa. 
We already enumerate explicitly the packages needed to cover the exa/tomic stack in the .travis.yml file anyway, so perhaps we should leverage conda to install the above dependencies not already picked up.

**Desktop (please complete the following information):**
 - OS: WSL (Ubuntu 14.04)
 - Browser: Chrome 71.0.3578.98
 - Version: discovered while on #135

**Additional context**
Thought it may be a suitable issue for exa instead. But since exa/tomic are tightly coupled, it makes sense that we directly git clone exa during the exatomic build.  Therefore it may only pertain to the exatomic build directly.

**Comment by avmarchenko** [comment]
This is a good catch. Like you write, one possible approach might be to modify the `requirements.txt` in `exa`. My gut reaction is that that is the most appropriate approach - a fix it at the source type approach. Waiting for others to weigh in.

**Comment by herbertludowieg** [comment]
Just want to bump this.
Is it still an issue?

**Comment by tjduigna** [comment]
Closing in favor of #231
