### ISSUE TITLE
Molecular orbital issues

### ISSUE THREAD

**Issue by herbertludowieg** [exa-analytics/exatomic#144]
**Describe the bug**
When adding molecular orbitals I get the error:
`TypeError: unsupported operand type(s) for *: 'numpy.ndarray' and 'Categorical'`
in the basis.BasisSet.primitives and functions return conditions.
I checked the dtypes of the uni.basis_set_order and for L it shows category instead of int

**To Reproduce**
This is actually the test code from the docs:
```
from exatomic.base import resource
from exatomic import gaussian
uni = gaussian.Output(resource('g09-ch3nh2-631g.out')).to_universe()
uni.add_molecular_orbitals(vector=range(10))
```
If I change the return value on the respective methods to `return n * n.index.get_level_values('L').map(mapper).astype(np.int64)` instead of `return n * n.index.get_level_values('L').map(mapper)` it works without any issues.

**Screenshots**
![exatomic_orbitals_issue_1](https://user-images.githubusercontent.com/22401527/53513252-bf433600-3a92-11e9-96a9-fc9a7ff1243b.png)
![exatomic_orbitals_issue_2](https://user-images.githubusercontent.com/22401527/53513280-ccf8bb80-3a92-11e9-935e-4fc0630b873d.png)
![exatomic_orbitals_issue_3](https://user-images.githubusercontent.com/22401527/53513284-cff3ac00-3a92-11e9-94b4-61f916c821e5.png)

**Desktop (please complete the following information):**
 - Windows
 - Opera
 - Git org master branch
 - Python 3.7.2

**Additional context**
I also updated all of the conda packages and there was no change

**Comment by herbertludowieg** [comment]
This actually seems to also be an issue with the tests. All of the orbital tests from what I saw on a quick skim seemed to have the same error. Should I just enforce the type or is there something deeper that needs to be changed?

**Comment by tjduigna** [comment]
Yeah it's definitely a bug.  Having not done any testing, I think the patch to ```.astype(np.int64)``` might work.  An alternative would be to use the internal API to ```._revert_categories()``` on the dataframe containing the categorical and then to ```._set_categories()``` when done with the computation before returning.  Honestly I think the astype is a cleaner solution.

Thanks for the catch!
