### ISSUE TITLE
Plotting NMR spectra and IR spectra

### ISSUE THREAD

**Issue by herbertludowieg** [exa-analytics/exatomic#155]
**Is your feature request related to a problem? Please describe.**
I think it would be cool if we could plot the NMR and IR spectra. We already parse all of the data so we would just have to have some plotting script. I think it would also be good to create some plotting directory that would have some base class for generating plots. I did this in a way in `exatomic.va.plot.PlotVROA`

**Describe the solution you'd like**
I think we can add a method to the respective classes that would take care of the arguments passed like figsize, x and y bounds, etc. For the NMR shifts we can add an extra parameter for the reference compound. Also, we'd have a variable to give lorentzian or gaussian lineshapes.

**Describe alternatives you've considered**
Creating the script in another jupyter notebook

**Comment by avmarchenko** [comment]
I like this idea. One difficulty is the balance of keeping a standard figure while allowing the user to take advantage of [insert plotting library]'s extensive flexibility. I'm not sure if you are thinking matplotlib or another plotting library, but one thing that would be extremely neat is to leverage some of the modern visualization tools for this like bokeh.

**Comment by herbertludowieg** [comment]
Yeah, the original idea was to use matplotlib, but bokeh looks so much nicer so I'll use that. Thank you!!
And yes, I'll do my best to keep that in mind.

**Comment by avmarchenko** [comment]
There are a few plotting options in this space. I think it is worth looking into plotly, bokeh, matplotlib+seaborn(?), d3.js (for apure JS solution), and holoviews. I'm not sure how much scope creep this ticket allows for and I'm not really sure what kind of 'solution' is intended. I think there would a lot of value in a solution that involves interactive, object oriented, visualization techniques. A nice function to wrap a particular use case (like the spectra listed above) would be a valuable addition.

**Comment by herbertludowieg** [comment]
The original plan was to mimic what is done in programs like WebMO where you can plot the spectra and be able to mouse over the plot area and get the data values. This seems trivial in bokeh so I think I'll stick to that.
