### ISSUE TITLE
Adding tests for codes

### ISSUE THREAD

**Issue by herbertludowieg** [exa-analytics/exatomic#161]
I want to make this issue to write down and track where we need to add tests to increase coverage where applicable. I would like to keep this open and update the issue by striking out any time that we add a test for the code in the list.

Tests to add:
 - ~~`exatomic.va.va.VA.zpvc`~~
 - `exatomic.plotter.plot` (We need them for all of the methods/functions in the code)
 - `exatomic.core.atom.Frequency`

**Comment by tjduigna** [comment]
Closing this as it's a bit tedious to have to track code coverage progress using an issue. Mentioned it in #231 to make sure visible code coverage is high priority. Of course, feel free to re-open it if you disagree.
