### ISSUE TITLE
Issue with atom.center

### ISSUE THREAD

**Issue by herbertludowieg** [exa-analytics/exatomic#166]
**Describe the bug**
There is an indexing issue in the `exatomic.atom.Atom.center` method. I believe that this comes from the way that we are currently trying to grab the index with `pandas.DataFrame.ix` as it is an index dependent lookup. It works as expected when we set `frame=0`, but anything else raises a `KeyError` exception.
I propose that we change `center = frame.ix[idx]` to `center = frame.iloc[idx]`. This is mentioned in the pandas docs

> A scalar index that is not found will raise a KeyError. Slicing is primarily on the values of the index when using [],ix,loc, and always positional when using iloc. The exception is when the slice is boolean, in which case it will always be positional.

**To Reproduce**
Minimal example to get the bug
```
from exatomic.base import resource
from exatomic.gaussian import Output

ed = Output(resource('g16-methyloxirane-def2tzvp-opt.out'))
ed.parse_atom()
ed.atom.center(idx=0)
```

**Expected behavior**
Returns the last frame with the first atom in the molecule centered on the origin.

**Desktop (please complete the following information):**
 - OS: WSL Ubuntu

**Comment by avmarchenko** [comment]
This seems like a good catch. I think those all places where ix is used should be changed to iloc. I believe that loc and iloc are strongly preferred over the x counterparts in pandas nowadays.

**Comment by herbertludowieg** [comment]
Yeah I think I'll take a look and see if I find any other places this happens.
Also, on a bit of a side note, the docs for the atom methods say that we return an `exatomic.Universe.atom` class. To me this doesn't seem to be the case as I can't use any of the methods like `to_xyz()`. An example would be:
```
from exatomic.base import resource
from exatomic.gaussian import Output

ed = Output(resource('g16-methyloxirane-def2tzvp-opt.out'))
ed.parse_atom()
centered = ed.atom.center(idx=0, frame=0)
centered.to_xyz()
```
Not sure if it would be good to add in the return argument `return Atom(result_of_operation)`
