### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by herbertludowieg** [exa-analytics/exatomic#174]
**Describe the bug**
Some of the tests are failing since the change from pandas 0.24.2 to 0.25. This issue is related to #173, where the categorical columns aren't handled correctly.

**To Reproduce**
Running the test suite.

**Expected behavior**
All passing

**Additional context**
Currently looking at the ADF output tests. I have noticed that with at least 1 output file on the resource directories the issue is not presented on an initial test (see jupyter notebook). There is one difference between the files, looking at the basis set section, but it would be odd for that to be the reason. Will do further testing with that thought in mind.
[adf-test.zip](https://github.com/exa-analytics/exatomic/files/4093668/adf-test.zip)

Update 3/19/2020
- All tests pass on travis for linux and osx
- Appveyor is having some issues for all but one of the runs. Might be related to the numba version.

**Comment by avmarchenko** [comment]
Closed by PR 176
