### ISSUE TITLE
exatomic doesn't support pandas 1.1

### ISSUE THREAD

**Issue by adamphil** [exa-analytics/exatomic#204]
**Describe the bug**
After a fresh install of the most recent pypi release of exa and exatomic with python version 3.7, exa imports successfully but exatomic import fails. Stack trace errors are attached:
[stack_trace.txt](https://github.com/exa-analytics/exatomic/files/5105676/stack_trace.txt)

**To Reproduce**
```
$ pip install exa
$ pip install exatomic
```

In python:
```
import exa
import exatomic
```

**Expected behavior**
Successful import of exatomic modules

**Desktop (please complete the following information):**
 - OS: WSL (Ubuntu 18.04)
 - Browser: Chrome (issue occurs inline as well as in notebook/browser)
 - python 3.7
- exa version 0.5.25
- exatomic version 0.5.6

**Comment by adamphil** [comment]
I may be wrong that this has to do with exa 0.5.25, but hopefully it isn't just a PEBKAC....

**Comment by avmarchenko** [comment]
Can you please list your version of numpy and pandas?

**Comment by avmarchenko** [comment]
https://github.com/exa-analytics/exa/pull/215

**Comment by avmarchenko** [comment]
Dependency fixed: to close this issues we need automated tests to confirm exatomic works with pandas>=1.1
