### ISSUE TITLE
Exatomic build failure

### ISSUE THREAD

**Issue by avmarchenko** [exa-analytics/exatomic#214]
**Describe the bug**
Build #623 (Job #623.1, 2, 3) are failing. 

**To Reproduce**
Run the build

**Expected behavior**
Build should succeed.

**Screenshots**
See travis-ci build 623 logs

**Desktop (please complete the following information):**
Only affects Python3.6+ on Linux

**Additional context**
Our build system attempts to do `python setup.py develop` rather than `python setup.py install`. Although there is an error regarding the JS dependencies, it may be possible that the root cause has to do with our Python side build config.

**Comment by avmarchenko** [comment]
We should migrate to Github actions for all CI tasks (travis and appv no longer have an unlimited cardboard tier).

**Comment by avmarchenko** [comment]
Since I'm not familiar with github actions I built a little expt https://github.com/avmarchenko/test-actions

**Comment by tjduigna** [comment]
Closing this in favor of #231 where progress toward github actions will be tracked.
