### ISSUE TITLE
Convert Molcas Orb to .47 File: "AttributeError: Please compute or set basis_set first"

### ISSUE THREAD

**Issue by stanistr** [exa-analytics/exatomic#228]
Hi,

I'm using Molcas to get spinorbitals for uranyl. I'm following the instructions in the supplemental of DOI: 10.1063/5.0004835, section 4, which tells you how to use eXatomic to convert a spinorbital to .47 file. 

The eXatomic script I am using:
--------------------------------------------------------
import exa
import exatomic
import pandas as pd
import numpy as np
import os
from exatomic import UniverseWidget as UW
from exatomic.algorithms.orbital import add_molecular_orbitals
from exatomic.base import resource
from exatomic import molcas
uni = exatomic.molcas.Output('seward.out')
uni.add_orb("Uranyl_Desym_ksw.DeSymOrb")
uni.overlap = molcas.HDF("Uranyl.rassi.h5").overlap
uni = uni.to_universe()
from exatomic import nbo
nbo = exatomic.nbo.Input.from_universe(uni)
nbo.write("uranyl.FILE47")
-------------------------------------------------------

seward.out: A C1 (no symmetry calcualtion) with BSSHow included to print the basis set information.
Uranyl_Desym_ksw.DeSymOrb: A SOSOrb file which has been desym using EXPBAS module of Molcas.
Uranyl.rassi.h5: Contains overlap matrix.

The error I get from eXatomic:
"AttributeError: Please compute or set basis_set first."
I've also attached the full read-out from eXatomic "error_message.txt".

I think the issue might be that the basis set information is not being read from the seward.out file, I'm likely doing something wrong and so any advice on how to resolve this error would be really appreciated. 

Thank you.

Attached Files:
[spinorb_python_script.txt](https://github.com/exa-analytics/exatomic/files/7138267/spinorb_python_script.txt)
[error_message.txt](https://github.com/exa-analytics/exatomic/files/7138275/error_message.txt)
[seward.txt](https://github.com/exa-analytics/exatomic/files/7138288/seward.txt)
[Uranyl_Desym_ksw_file.txt](https://github.com/exa-analytics/exatomic/files/7138320/Uranyl_Desym_ksw_file.txt)

**Comment by tjduigna** [comment]
Thanks for posting this issue and for the additional files. From the error messages, it looks like the first error is this:
```
parse_atom failed with: Cannot convert non-finite values (NA or inf) to integer
```
Upon inspection of seward.txt, it appears you are using a numerical label for one of the oxygen atoms in the uranyl complex.  This causes a problem when parsing the atom table, which is required for the basis set table. 

The parsing is admittedly brittle and happy to accept a PR to support this edge case in the parsing, or you may be able to rerun just the seward module replacing `02` with `O2`. I don't remember if the atomic labels are referenced explicitly in the orbital files.

**Comment by stanistr** [comment]
Really appreciate you taking the time to help! Such a rookie mistake on my side, fixing the mistake in the seward file solved the issue and eXatomic runs perfectly.
