### ISSUE TITLE
Exa migration design

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exatomic#230]
In-housing exa can be accomplished in a number of ways, here are 2 options.

1. Basically `git mv exa/exa/ exatomic/` and then make sure imports work and tests are brought in.

2. Flatten the package structure and re-organize the exa project as if it were natively developed within the exatomic project structure. 

Personally, I am a fan of 1 because it still treats exa as an "external" package, and it is easy to update setup.py to install two package namespaces. Though option 2 is worth considering if we don't believe we'll ever successfully remove exa from the exatomic API. That way it doesn't live on as a warty bolt-on.

**Comment by avmarchenko** [comment]
Excerpt from offline discussion outlining my plan:

Okay, regarding option 2 (in issue #230) can I do a quick expt on option 2 with the long term view that we'll have future issues removing exa bloat from exatomic (stuff like removing unnecessary class hierarchies, unnecessary functions unnecessary typing etc)?
It would be really nice to do a way with the complex parent child grandchild class inheritance that we have going on and move to something more functional in the future and I think option two is more conducive to that long-term
