### ISSUE TITLE
Field buggy with diferent ndims 

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exatomic#38]
If I have two rows with different parameters in the field table marching cubes returns nothing.

**Comment by alexvmarch** [comment]
What is stored in the widgets trait values

**Comment by tjduigna** [comment]
['ufield3d_nx'] returns '[[76,101]]' as expected.
['oz'] returns '-17' as expected (as we compress to translate then expand on JS side)
['ufield3d_dxi'] returns '[[0.32,0.24]]' as expected.
And it looks like ['field_values'] is '[[num,num,num...' so assuming that is correctly indexed as well.

**Comment by tjduigna** [comment]
This cropped up again (user error on my part this time) with the following behavior. On the JS side, when calling the gen_array function, if ox wasn't flattened to a single value (in the case that all the values are the same) then gen_array returns arrays of NaNs. 

To fix --

Inside render_field() in app.js var ox, oy, oz must be selected by atomicfield index if not single valued.

**Comment by avmarchenko** [comment]
NA #60
