### ISSUE TITLE
rcParams-like for styling to circumvent the gui

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exatomic#39]
In the context of the workflow for snapping shots of isosurfaces: It is easy enough to save the canvas as a png when it is set up nice. Now say I have my set of defaults; the camera position, the field index, the material of choice for atoms (spheres) and the material of choice for surfaces, etc. These are not the defaults in the GUI and as such require manual setting each time a universe is loaded. This precludes automation of the process by requiring input each time. We should think about how to programmatically (sp?) set these values before the rendering of a universe.

Although I am not sure this solves the automation problem, it would certainly be useful regardless of this use case.

**Comment by tjduigna** [comment]
PS -- maybe this belongs in exa?

**Comment by alexvmarch** [comment]
Possibly; but it is also application dependent. I would vote for developing the gui further - options for cam pos, material choices, etc. and then be able to specify the defaults via the _widget traits on the python side (with suitable defaults like we have now). With that infrastructure in place we can have params like options.

As an example, in my custom branch, I am using an attribute on the container called display which is a dictionary that has some options such as which coordinates I want to visualize (atom, visual_atom, projected_atom). This could be expanded to include default material choices, coordinate axis, etc.

**Comment by tjduigna** [comment]
Okay cool I will model my use case after your example. How does access an issue once it's closed?

**Comment by alexvmarch** [comment]
You can filter issues by "is:issue is:closed". I don't know if that is the best idea, but from a pythonic perspective, following the dictionary model of rcParams makes sense (though I wouldn't call it rcparams). If you think of a better play post it.

**Comment by alexvmarch** [comment]
Commit #804194c59f8e4bd0b09ea3b959e03fff763e3c60 has a template of how container display parameters may work.

**Comment by avmarchenko** [comment]
No longer (currently) applicable.
