### ISSUE TITLE
Visual bugs for field viewing

### ISSUE THREAD

**Issue by avmarchenko** [exa-analytics/exatomic#56]
This may be relevant!

https://github.com/mrdoob/three.js/issues/2593

Essentially we need to smoothen z fighting (as it is called) issues between objects within our threejs scene.

**Comment by alexvmarch** [comment]
http://stackoverflow.com/questions/31226344/three-js-edgeshelper-showing-certain-diagonal-lines-on-collada-model/31232508#31232508

Referenced in that issue.

**Comment by tjduigna** [comment]
This SO post offers a nice summary of their experience using it for an astronomical model of the solar system and they had issues with the numbers being so large that the objects started to "shimmer"

http://stackoverflow.com/questions/14761595/three-js-objects-shimmering-at-large-distances

The easiest solution would be to set the near argument to the camera to 1. It seems to clean up quite nicely on a few cubes tested. Don't think it's the full solution though

**Comment by avmarchenko** [comment]
No longer (currently) applicable (fixes in three.js and face normals, and MC rewrite have likely contributed to resolving this issue).
