### ISSUE TITLE
Transformation manipulations for the atom table

### ISSUE THREAD

**Issue by avmarchenko** [exa-analytics/exatomic#86]
It would be convenient to perform operations such as rotations and translations on the atom table via convenient methods:

```
uni.atom.rotate(theta=10)    # degrees
```

Suppose that theta is the angle in the xy plane, this function would rotate each frame's atomic coordinates 10 degrees in the xy plane. Another example:

```
uni.atom.translate(dx=-10)
```

This example would translate all x coordinates by minus 10 units. These functions could be extended to other convenient methods like `uni.atom.center(.....)`.

**Comment by herbertludowieg** [comment]
Do you think it's at all useful if we add an inplace option? I feel that it would be pretty harmless with the rotation and the center function. For the translation function I am thinking there could be an issue with the visualization if they put the wrong value and it gets displaced way off the screen.
