### ISSUE TITLE
An automated way for Editors to handle exceptions

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exatomic#88]
I think this might work out nicely. It inherits the standard metaclass for editor (and universe) and just checks for parse methods, then decorates them with a try/except that will print the stack trace so that we don't lose that debugging information. That way when the AttributeError is thrown for not having a property set, we will see where the parsing function went wrong. Additionally it prevents the boilerplate of many try/excepts within the parse methods themselves and/or manual decorators. It may be too generic by catching all exceptions. What do you think?

```python
from types import FunctionType
from logging import exception as stacktrace

class ParseMeta(exatomic.container.Meta):
    @classmethod
    def check_parse(cls, func):
        def wrapper(cls):
            try:
                return func(cls)
            except Exception as e:
                stacktrace('{} failed with error: {}'.format(func.__name__, e))
            return
        return wrapper
    
    def __new__(cls, name, bases, clsdict):
        for k, v in clsdict.items():
            if isinstance(v, FunctionType) and k.startswith('parse_'):
                clsdict[k] = cls.check_parse(v)
        return super(ParseMeta, cls).__new__(cls, name, bases, clsdict)
```

**Comment by avmarchenko** [comment]
This issue deals with the problem of creating a container object from an editor object. In many cases it is possible to create a minimal container from an editor even if some parts of the data are not parsed. I am not sure that dealing with this by modifying the editor's class definition on import is the best way. I do like use of logging failed parse calls, but I don't understand why this can't be handled when an editor.to_container() like call is made with a single try/except? If a call to parse a particular object is called via editor.parse_feature() and it fails, it fails with the exception without the need for this machinery no?

**Comment by tjduigna** [comment]
I agree. Keep it simple :)
