### ISSUE TITLE
Small bug in XYZ parser

### ISSUE THREAD

**Issue by tjduigna** [exa-analytics/exatomic#89]
YXZ breaks with the following error message if there are 2 blank lines at the end of a single geometry. 

line 45, in parse_atom
    counts = nats.values.astype(np.int64)
ValueError: cannot convert float NaN to integer

Just need to dropna() on nats at some point before line 45, but needs tests.

**Comment by avmarchenko** [comment]
XYZ parsing has been redone, with tests, that are currently passing. Will reopen if this appears again.
